## default for all profiles
[default]
address = "0.0.0.0"
port = 8000
limits = { forms = "64KiB", json = "1MiB" }

## set only when compiled in debug mode, i.e, `cargo build`
[debug]
address = "127.0.0.1"
port = 8000
