[package]
name = "controller"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5.1", features = ["secrets", "json", "secrets", "tls"] }
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
